name: Composer, Linter, and Tests

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: "8.1"
          tools: composer, cs2pr

      - name: 🔍 Validate composer.json and composer.lock
        run: composer validate

      - name: 📦 Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: ✨ Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=PSR2 --extensions=php --exclude=Generic.Files.LineLength src

      - name: 🧪 Run PHPUnit tests
        run: composer run-script test
