name: Composer, Linter, and Tests

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: "8.1"
          tools: composer, cs2pr

      - name: 🔍 Validate composer.json and composer.lock
        run: composer validate

      - name: 📦 Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: ✨ Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=PSR2 --extensions=php --exclude=Generic.Files.LineLength src

      - name: 🧪 Run PHPUnit tests
        run: composer run-script test
